[package]
name = "c2o3fe2"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = ["teamserver","operator", "agent"]

[workspace.dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
